version: 2

before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - id: rest
    dir: .
    main: ./cmd/client/main.go
    binary: rest
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64

archives:
  - id: default
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip
      - goos: '*'
        format: tar.gz
    wrap_in_directory: true
    files:
      - LICENSE
      - README.md

release:
  github:
    owner: egeuysall
    name: rest

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
