version: 2

before:
  hooks:
    - (cd backend && go mod tidy)
    - (cd backend && go generate ./...)

builds:
  - id: rest
    dir: ./backend
    main: ./cmd/client/main.go
    binary: rest
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64

archives:
  - id: default
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format: tar.gz
    wrap_in_directory: true
    replacements:
      amd64: x86_64
      386: i386
      darwin: macOS
      linux: Linux
    files:
      - LICENSE
      - README.md

release:
  github:
    owner: egeuysall
    name: rest

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
